[tools]
bun = "1.2.18"
node = "24.3.0"
python = "3.13.5"
"npm:opencode-ai" = "0.1.192"
"npm:typescript-language-server" = "4.3.4"

[env]
_.file = "~/.config/mise/.env"
DO_NOT_TRACK=1
HOMEBREW_NO_ANALYTICS=1
