[tools]
node = "24.2.0"
python = "3.13.5"
"aqua:BurntSushi/ripgrep" = "14.1.1"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:atuinsh/atuin" = "18.6.1"
"aqua:dandavison/delta" = "0.18.2"
"aqua:jesseduffield/lazydocker" = "0.24.1"
"aqua:jesseduffield/lazygit" = "0.52.0"
"aqua:jqlang/jq" = "1.8.0"
"aqua:junegunn/fzf" = "0.62.0"
"aqua:neovim/neovim" = "0.11.2"
"aqua:noborus/ov" = "0.41.0"
"aqua:sharkdp/bat" = "0.25.0"
"aqua:sharkdp/fd" = "10.2.0"
"aqua:starship/starship" = "1.23.0"
"aqua:twpayne/chezmoi" = "2.62.6"
"aqua:zk-org/zk" = "0.15.1"
"npm:opencode-ai" = "0.1.117"
"npm:@anthropic-ai/claude-code" = "1.0.31"
"npm:typescript-language-server" = "4.3.4"

[env]
_.file = "~/.config/mise/.env"

