[tools]
node = "24.3.0"
python = "3.13.5"
"aqua:BurntSushi/ripgrep" = "14.1.1"
"aqua:dandavison/delta" = "0.18.2"
"aqua:jesseduffield/lazydocker" = "0.24.1"
"aqua:jesseduffield/lazygit" = "0.52.0"
"aqua:jqlang/jq" = "1.8.0"
"aqua:junegunn/fzf" = "0.63.0"
"aqua:noborus/ov" = "0.42.0"
"aqua:sharkdp/bat" = "0.25.0"
"aqua:sharkdp/fd" = "10.2.0"
"aqua:twpayne/chezmoi" = "2.62.7"
"aqua:zk-org/zk" = "0.15.1"
"npm:opencode-ai" = "0.1.166"
"npm:@anthropic-ai/claude-code" = "1.0.35"
"npm:typescript-language-server" = "4.3.4"

[env]
_.file = "~/.config/mise/.env"
DO_NOT_TRACK=1
HOMEBREW_NO_ANALYTICS=1
