[tools]
bun = "1.2.19"
node = "24.4.1"
python = "3.13.5"
"npm:opencode-ai" = "0.3.79"
"npm:@sourcegraph/amp" = "latest"
"npm:typescript-language-server" = "4.3.4"

[env]
_.file = "~/.config/mise/.env"
DO_NOT_TRACK=1
HOMEBREW_NO_ANALYTICS=1
