[tools]
node = "24.1.0"
"aqua:atuinsh/atuin" = "18.6.1"
"aqua:sharkdp/bat" = "0.25.0"
"aqua:twpayne/chezmoi" = "2.62.5"
# "aqua:crates.io/eza" = "0.20.18"
"aqua:sharkdp/fd" = "10.2.0"
"aqua:junegunn/fzf" = "0.62.0"
"aqua:dandavison/delta" = "0.18.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:jesseduffield/lazygit" = "0.51.1"
"aqua:jesseduffield/lazydocker" = "0.24.1"
"aqua:neovim/neovim" = "0.11.1"
"aqua:noborus/ov" = "0.41.0"
"aqua:BurntSushi/ripgrep" = "14.1.1"
"aqua:starship/starship" = "1.23.0"
"aqua:zellij-org/zellij" = "0.42.2"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"npm:@anthropic-ai/claude-code" = "1.0.6"

[env]
_.file = "~/.config/mise/.env"

