gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#b15c00"
      - "bold"
    inactiveBorderColor:
      - "#4094a3"
    searchingActiveBorderColor:
      - "#b15c00"
      - "bold"
    optionsTextColor:
      - "#2e7de9"
    selectedLineBgColor:
      - "#b7c1e3"
    cherryPickedCommitFgColor:
      - "#2e7de9"
    cherryPickedCommitBgColor:
      - "#9854f1"
    markedBaseCommitFgColor:
      - "#2e7de9"
    markedBaseCommitBgColor:
      - "#8c6c3e"
    unstagedChangesColor:
      - "#c64343"
    defaultFgColor:
      - "#3760bf"

git:
  paging:
    colorArg: always
    pager: delta --paging=never
  commit:
    signOff: true
customCommands:
  - key: "b"
    command: "gh browse"
    context: "files"
  - key: "b"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
notARepository: skip
refresher:
  refreshInterval: 5
  fetchInterval: 3600
