gui:
  theme:
    activeBorderColor:
      - "#c6a0f6"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#c6a0f6"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"

  authorColors:
    "*": "#b7bdf8"

git:
  paging:
    colorArg: always
    pager: delta --paging=never
  commit:
    signOff: true
customCommands:
  - key: "b"
    command: "gh browse"
    context: "files"
  - key: "b"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
notARepository: skip
refresher:
  refreshInterval: 5
  fetchInterval: 3600
