gui:
  theme:
    activeBorderColor:
      - "#8839ef"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#ccd0da"
    cherryPickedCommitBgColor:
      - "#bcc0cc"
    cherryPickedCommitFgColor:
      - "#8839ef"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#df8e1d"

  authorColors:
    "*": "#7287fd"

git:
  paging:
    colorArg: always
    pager: delta --paging=never
  commit:
    signOff: true
customCommands:
  - key: "b"
    command: "gh browse"
    context: "files"
  - key: "b"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
notARepository: skip
refresher:
  refreshInterval: 5
  fetchInterval: 3600
