add_newline = true
command_timeout = 750

format = """
$directory $git_branch $git_status $git_metrics $kubernetes$line_break$character
"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[git_branch]
format = "[ $branch]($style) "

[git_metrics]
disabled = false
added_style = 'bold green'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[kubernetes]
disabled = false
format = '[ 󱃾 $context]($style) '
